### ISSUE TITLE
Strange error after upgrading Node

### ISSUE THREAD

**Issue by phil-highrez** [boikedamhuis/homebridge-frontier-silicon#5]
I just upgraded Node (to v14.15.1) and Im now getting a strange error in Homebridge relating to the homebridge-frontier-silicon-plugin (latest version)

NOTE: I have checked and the "request" module is listed under the hombridge/node_modules

Any ideas? It would be a shame to loose access to my two radios!

[09/12/2020, 22:49:07] ====================
[09/12/2020, 22:49:07] ERROR LOADING PLUGIN homebridge-frontier-silicon-plugin:
[09/12/2020, 22:49:07] Error: Cannot find module 'request'
Require stack:
- /usr/local/lib/node_modules/homebridge-frontier-silicon-plugin/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-frontier-silicon-plugin/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[09/12/2020, 22:49:07] ====================

**Comment by phil-highrez** [comment]
I think I've fixed it.

For anyone else, from the homebridge folder (in my case /var/lib/homebridge) I ran the following two commands...

>npm init --yes
>sudo npm install --save request -g
